restaurant/urls.py
from django.urls import path

from restaurant.views import (
    index,
    DishTypeListView,
    DishTypeCreateView,
    DishTypeUpdateView,
    DishTypeDeleteView,
    DishListView,
    DishDetailView,
    DishCreateView,
    DishUpdateView,
    DishDeleteView,
    CookListView,
    CookDetailView,
    CookCreateView,
    CookUpdateView,
    CookDeleteView,
    ToggleAssignToDishView,
)


urlpatterns = [
    path("", index, name="index"),
    path(
        "dish-types/",
        DishTypeListView.as_view(),
        name="dish-type-list",
    ),
    path(
        "dish-types/create/",
        DishTypeCreateView.as_view(),
        name="dish-type-create",
    ),
    path(
        "dish-types/<int:pk>/update/",
        DishTypeUpdateView.as_view(),
        name="dish-type-update",
    ),
    path(
        "dish-types/<int:pk>/delete/",
        DishTypeDeleteView.as_view(),
        name="dish-type-delete",
    ),
    path(
        "dishes/",
        DishListView.as_view(),
        name="dish-list",
    ),
    path(
        "dishes/<int:pk>/",
        DishDetailView.as_view(),
        name="dish-detail",
    ),
    path(
        "dishes/create/",
        DishCreateView.as_view(),
        name="dish-create"
    ),
    path(
        "dishes/<int:pk>/update/",
        DishUpdateView.as_view(),
        name="dish-update"
    ),
    path(
        "dishes/<int:pk>/delete/",
        DishDeleteView.as_view(),
        name="dish-delete"
    ),
    path(
        "dishes/<int:pk>/toggle-assign/",
        ToggleAssignToDishView.as_view(),
        name="toggle-dish-assign",
    ),
    path(
        "cooks/",
        CookListView.as_view(),
        name="cook-list",
    ),
    path(
        "cooks/<int:pk>/",
        CookDetailView.as_view(),
        name="cook-detail",
    ),
    path(
        "cooks/create/",
        CookCreateView.as_view(),
        name="cook-create"
    ),
    path(
        "cooks/<int:pk>/update/",
        CookUpdateView.as_view(),
        name="cook-update",
    ),
    path(
        "cooks/<int:pk>/delete/",
        CookDeleteView.as_view(),
        name="cook-delete",
    ),
    ]

app_name = "restaurant"

restaurant_kitchen_service/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from restaurant.views import RegisterUserView

urlpatterns = [
    path("admin/", admin.site.urls),
    path("", include("restaurant.urls", namespace="restaurant")),
    path("accounts/", include("django.contrib.auth.urls")),
    path("register/", RegisterUserView.as_view(), name="register"),
] + static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

restaurant/models.py
from django.db import models
from django.urls import reverse
from django.contrib.auth.models import AbstractUser
from django.core.validators import MinValueValidator, MaxValueValidator


class DishType(models.Model):
    name = models.CharField(max_length=255, unique=True)

    class Meta:
        ordering = ["name"]

    def __str__(self):
        return f"{self.name}"


class Cook(AbstractUser):
    years_of_experience = models.IntegerField(
        blank=True,
        null=True,
        validators=[MinValueValidator(0), MaxValueValidator(50)]
    )

    class Meta:
        verbose_name = "cook"
        verbose_name_plural = "cooks"

    def __str__(self):
        return f"{self.username} ({self.first_name} {self.last_name})"

    def get_absolute_url(self):
        return reverse("restaurant:cook-detail", kwargs={"pk": self.pk})


class Dish(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField(blank=True, null=True)
    price = models.DecimalField(max_digits=5, decimal_places=2)
    dish_type = models.ForeignKey(DishType, on_delete=models.CASCADE)
    cooks = models.ManyToManyField(Cook, related_name="dishes")

    class Meta:
        verbose_name = "dish"
        verbose_name_plural = "dishes"

    def __str__(self):
        return self.name

    def get_absolute_url(self):
        return reverse("restaurant:dish-detail", kwargs={"pk": self.pk})

restaurant/forms.py
from django import forms
from django.contrib.auth import get_user_model
from django.contrib.auth.forms import UserCreationForm

from restaurant.models import Dish, Cook


class DishForm(forms.ModelForm):
    cooks = forms.ModelMultipleChoiceField(
        queryset=get_user_model().objects.all(),
        widget=forms.CheckboxSelectMultiple,
    )

    class Meta:
        model = Dish
        fields = "__all__"
        widgets = {
            "description": forms.Textarea(attrs={"rows": 1, "cols": 30}),
        }


class CookCreationForm(UserCreationForm):
    class Meta(UserCreationForm.Meta):
        model = Cook
        fields = UserCreationForm.Meta.fields + (
            "first_name",
            "last_name",
            "email",
            "years_of_experience",
        )


class DishTypeSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class DishSearchForm(forms.Form):
    name = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by name"})
    )


class CookSearchForm(forms.Form):
    username = forms.CharField(
        max_length=255,
        required=False,
        label="",
        widget=forms.TextInput(attrs={"placeholder": "Search by username"})
    )


class SignUpForm(UserCreationForm):
    username = forms.CharField(
        widget=forms.TextInput(
            attrs={
                "placeholder": "Username",
                "class": "form-control"
            }
        ))
    email = forms.EmailField(
        widget=forms.EmailInput(
            attrs={
                "placeholder": "Email",
                "class": "form-control"
            }
        ))
    password1 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password",
                "class": "form-control"
            }
        ))
    password2 = forms.CharField(
        widget=forms.PasswordInput(
            attrs={
                "placeholder": "Password check",
                "class": "form-control"
            }
        ))

    class Meta:
        model = Cook
        fields = ("username", "email", "password1", "password2")

restaurant/views.py
from django.contrib.auth import authenticate
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.http import HttpResponseRedirect
from django.shortcuts import render
from django.urls import reverse_lazy
from django.views import generic, View


from restaurant.forms import DishForm, CookCreationForm, DishTypeSearchForm, DishSearchForm, CookSearchForm, SignUpForm
from restaurant.models import Cook, Dish, DishType


@login_required
def index(request):
    """View function for the home page of the site."""

    num_cooks = Cook.objects.count()
    num_dishes = Dish.objects.count()
    num_dish_types = DishType.objects.count()

    num_visits = request.session.get("num_visits", 0)
    request.session["num_visits"] = num_visits + 1

    context = {
        "num_cooks": num_cooks,
        "num_dishes": num_dishes,
        "num_dish_types": num_dish_types,
        "num_visits": num_visits + 1,
    }

    return render(request, "restaurant/index.html", context=context)


class DishTypeListView(LoginRequiredMixin, generic.ListView):
    model = DishType
    context_object_name = "dish_type_list"
    template_name = "restaurant/dish_type_list.html"
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")

        context["search_form"] = DishTypeSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = DishType.objects.all()
        form = DishTypeSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishTypeCreateView(LoginRequiredMixin, generic.CreateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dish-type-list")
    template_name = "restaurant/dish_type_form.html"


class DishTypeUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = DishType
    fields = "__all__"
    success_url = reverse_lazy("restaurant:dish-type-list")
    template_name = "restaurant/dish_type_form.html"


class DishTypeDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = DishType
    success_url = reverse_lazy("restaurant:dish-type-list")
    template_name = "restaurant/dish_type_confirm_delete.html"


class DishListView(LoginRequiredMixin, generic.ListView):
    model = Dish
    paginate_by = 5
    queryset = Dish.objects.all().select_related("dish_type")

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        name = self.request.GET.get("name", "")

        context["search_form"] = DishSearchForm(
            initial={"name": name}
        )
        return context

    def get_queryset(self):
        queryset = Dish.objects.all().order_by("id")
        form = DishSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(name__icontains=form.cleaned_data["name"])
        return queryset


class DishDetailView(LoginRequiredMixin, generic.DetailView):
    model = Dish


class DishCreateView(LoginRequiredMixin, generic.CreateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dish-list")


class DishUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Dish
    form_class = DishForm
    success_url = reverse_lazy("restaurant:dish-list")


class DishDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Dish
    success_url = reverse_lazy("restaurant:dish-list")


class CookListView(LoginRequiredMixin, generic.ListView):
    model = Cook
    paginate_by = 5

    def get_context_data(self, *, object_list=None, **kwargs):
        context = super().get_context_data(**kwargs)
        username = self.request.GET.get("username", "")

        context["search_form"] = CookSearchForm(
            initial={"username": username}
        )
        return context

    def get_queryset(self):
        queryset = Cook.objects.all().order_by("id")
        form = CookSearchForm(self.request.GET)
        if form.is_valid():
            return queryset.filter(
                username__icontains=form.cleaned_data["username"]
            )
        return queryset


class CookDetailView(LoginRequiredMixin, generic.DetailView):
    model = Cook
    queryset = Cook.objects.all().prefetch_related("dishes__dish_type")


class CookCreateView(LoginRequiredMixin, generic.CreateView):
    model = Cook
    form_class = CookCreationForm


class CookUpdateView(LoginRequiredMixin, generic.UpdateView):
    model = Cook
    fields = "__all__"
    success_url = reverse_lazy("restaurant:cook-list")


class CookDeleteView(LoginRequiredMixin, generic.DeleteView):
    model = Cook
    success_url = reverse_lazy("restaurant:cook-list")


class ToggleAssignToDishView(LoginRequiredMixin, View):
    def get(self, request, pk):
        return self.post(request, pk)

    def post(self, request, pk):
        cook = Cook.objects.get(id=request.user.id)
        if Dish.objects.get(id=pk) in cook.dishes.all():
            cook.dishes.remove(pk)
        else:
            cook.dishes.add(pk)
        return HttpResponseRedirect(reverse_lazy("restaurant:dish-detail", args=[pk]))


class RegisterUserView(View):
    def get(self, request):
        form = SignUpForm()
        return render(request, "registration/register.html", {"form": form})

    def post(self, request):
        msg = None
        success = False
        form = SignUpForm(request.POST)
        if form.is_valid():
            form.save()
            username = form.cleaned_data.get("username")
            raw_password = form.cleaned_data.get("password1")
            user = authenticate(username=username, password=raw_password)

            msg = "Account created successfully."
            success = True
        else:
            msg = "Form is not valid"
        return render(request, "registration/register.html", {"form": form, "msg": msg, "success": success})

templates/restaurant/cook_confirm_delete.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
  <header class="bg-gradient-dark">
    <div class="page-header" style="background-image: url('{{ ASSETS_ROOT }}/img/cook_list.jpg'); min-height: 25vh;">
      <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container">
          <div class="row justify-content-center">
          </div>
        </div>
    </div>
  </header>

<section>
  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column" style="text-align:center">
        <h2 class="text-grey">Delete cook - {{ cook.username }}?</h2>
        <form role="form" method="post" autocomplete="off">
          <div class="card-body">
            <div class="row justify-content-center">
              <div class="col-md-3">
                <div class="input-group input-group-dynamic mb-4">
                  {% csrf_token %}
                </div>
              </div>
            </div>
            <input type="submit" value="Submit" class="btn btn-danger mr-2">
            <a href="{% url 'restaurant:cook-list' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/restaurant/cook_detail.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}

  <header class="bg-gradient-dark">
    <div class="page-header" style="background-image: url('{{ ASSETS_ROOT }}/img/cook_list.jpg'); min-height: 40vh;">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">{{ cook.username }}</h1>
            <a href="{% url 'restaurant:cook-delete' pk=cook.id %}" class="btn btn-danger link-to-page">
                Delete
              </a>
              <a href="{% url 'restaurant:cook-update' pk=cook.id %}" class="btn btn-secondary link-to-page">
                Update
              </a>
          </div>
        </div>
      </div>
    </div>
  </header>

<style>
.cook_info {
  padding-left: 200px;
    font-family: Georgia, serif;
}
</style>

<div class="cook_info">
  <h4>Name</h4><p>{{ cook.first_name }} {{ cook.last_name }}</p>
  <h4>Years of experience</h4><p>{{ cook.years_of_experience }} years</p>
  <hr>
  <div class="ml-3">
    <h4>Dishes</h4>

    {% for dish in cook.dishes.all %}
        <hr>
        <p><strong>Name:</strong> {{ dish.name }}</p>
        <p><strong>Dish type:</strong> {{ dish.dish_type.name }}</p>
        <p class="text-muted"><strong>Id:</strong> {{dish.id}}</p>

    {% empty %}
      <p>No dishes!</p>
    {% endfor %}
  </div>
</div>

{% endblock %}

templates/restaurant/cook_form.html
{% extends "layouts/base.html" %}
{% load static %}
{% load crispy_forms_filters %}


{% block content %}
<link rel="stylesheet" href="{% static 'css/styles.css' %}">
  <header class="bg-gradient-dark">
    <div class="page-header" style="background-image: url('{{ ASSETS_ROOT }}/img/cook_list.jpg'); min-height: 25vh;">
      <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container">
          <div class="row justify-content-center">
          </div>
        </div>
    </div>
  </header>

  <section>
    <div class="container py-4 overflow-hidden">
      <div class="row">
        <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
          <h3 class="text-center">{{ object|yesno:"Update,Create" }} cook</h3>
          <form role="form" method="post" autocomplete="off">
            <div class="card-body">
              <div class="row justify-content-center">
                <div class="col-md-6">
                  <div class="input-group input-group-dynamic mb-4">
                    {% csrf_token %}
                      {{ form.username|as_crispy_field }}
                      {{ form.first_name|as_crispy_field }}
                      {{ form.last_name|as_crispy_field }}
                      {{ form.email|as_crispy_field }}
                  </div>
                  <div class="input-group input-group-dynamic mb-4">
                    {{ form.years_of_experience|as_crispy_field }}
                  </div>
                </div>
              </div>
              <div class="d-flex justify-content-center">
                <input type="submit" value="Submit" class="btn btn-primary" style="margin-right: 10px;">
                <a href="{% url 'restaurant:cook-list' %}" class="btn btn-secondary">Cancel</a>
              </div>
            </div>
          </form>
        </div>
      </div>
    </div>
  </section>

{% endblock %}

templates/restaurant/cook_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}

    <header class="bg-gradient-dark">
    <div class="page-header" style="background-image: url('{{ ASSETS_ROOT }}/img/cook_list.jpg'); min-height: 50vh;">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">Cook list</h1>
            <a href="{% url 'restaurant:cook-create' %}" class="btn btn-primary link-to-page">Create</a>
          </div>
        </div>
      </div>
    </div>
  </header>


  {% include "includes/search_form.html" %}

  {% if cook_list %}
    <div class="card-body p-0">
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
          <div class="table-responsive">
            <div class="customer-scroll" style="height:auto;position:relative;">
              <table class="table table-hover m-b-0" style="table-layout: auto;">
                <thead>
                  <tr>
                    <th><span>ID</span></th>
                    <th><span>Username <a class="help" data-toggle="popover"><i class="feather icon-help-circle f-16"></i></a></span></th>
                    <th><span>First name <a class="help" data-toggle="popover"><i class="feather icon-help-circle f-16"></i></a></span></th>
                    <th><span>Last name<a class="help" data-toggle="popover"><i class="feather icon-help-circle f-16"></i></a></span></th>
                    <th><span>Years of experience<a class="help" data-toggle="popover"><i class="feather icon-help-circle f-16"></i></a></span></th>
                  </tr>
                </thead>
                <tbody>
                {% for cook in cook_list %}
                  <tr>
                    <td>
                      {{ cook.id }}
                    </td>
                    <td>
                      <a href="{{ cook.get_absolute_url }}">{{ cook.username }} {% if user == cook %} (Me){% endif %}</a>
                    </td>
                    <td>
                      {{ cook.first_name }}
                    </td>
                    <td>
                      {{ cook.last_name }}
                    </td>
                    <td>
                      {{ cook.years_of_experience }}
                    </td>
                  </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>


  {% else %}
      <p>There are no cooks in the restaurant.</p>
  {% endif %}
{% endblock %}

templates/restaurant/dish_confirm_delete.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}
  <header class="bg-gradient-dark">
    <div class="page-header" style="background-image: url('{{ ASSETS_ROOT }}/img/dish_list.jpg'); min-height: 25vh;">
      <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container">
          <div class="row justify-content-center">
          </div>
        </div>
    </div>
  </header>

<section>
  <div class="container py-4">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column" style="text-align:center">
        <h2 class="text-grey">Delete dish - {{ dish.name }}?</h2>
        <form role="form" method="post" autocomplete="off">
          <div class="card-body">
            <div class="row justify-content-center">
              <div class="col-md-3">
                <div class="input-group input-group-dynamic mb-4">
                  {% csrf_token %}
                </div>
              </div>
            </div>
            <input type="submit" value="Submit" class="btn btn-danger mr-2">
            <a href="{% url 'restaurant:dish-list' %}" class="btn btn-secondary">Cancel</a>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/restaurant/dish_detail.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}

  <header class="bg-gradient-dark">
    <div class="page-header" style="background-image: url('{{ ASSETS_ROOT }}/img/dish_list.jpg'); min-height: 40vh;">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">{{ dish.name }}</h1>
            <a href="{% url 'restaurant:dish-delete' pk=dish.id %}" class="btn btn-danger link-to-page">
                Delete
              </a>
              <a href="{% url 'restaurant:dish-update' pk=dish.id %}" class="btn btn-secondary link-to-page">
                Update
              </a>
          </div>
        </div>
      </div>
    </div>
  </header>

<style>
.dish_info {
  padding-left: 200px;
    font-family: Georgia, serif;
}
</style>

<div class="dish_info">
  <h3>Dish type</h3>
    <p>
      {{ dish.dish_type.name }}
    </p>
  <h3>Description</h3>
    <p>
    {{ dish.description }}
    </p>
  <h3>
    Cooks
      {% if dish in user.dishes.all %}
      <a href="{% url 'restaurant:toggle-dish-assign' pk=dish.id %}" class="btn btn-danger link-to-page">
        Delete me from this dish
      </a>
    {% else %}
      <a href="{% url 'restaurant:toggle-dish-assign' pk=dish.id %}" class="btn btn-success link-to-page">
        Assign me to this dish
      </a>
    {% endif %}
  </h3>
  <hr>
  <ul>
    {% for cook in dish.cooks.all %}
      <li>
        {{ cook.username }}
        ({{ cook.first_name }} {{ cook.last_name }}, {{ cook.years_of_experience }} years of experience)
      </li>
    {% endfor %}
  </ul>
</div>

{% endblock %}

templates/restaurant/dish_form.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}

<style>
    .input-group input[type="checkbox"] {
    width: 20px;
}
</style>
{% block content %}
  <header class="bg-gradient-dark">
    <div class="page-header" style="background-image: url('{{ ASSETS_ROOT }}/img/dish_list.jpg'); min-height: 25vh;">
      <span class="mask bg-gradient-dark opacity-6"></span>
        <div class="container">
          <div class="row justify-content-center">
          </div>
        </div>
    </div>
  </header>

  <section>
  <div class="container py-4 overflow-hidden">
    <div class="row">
      <div class="col-lg-7 mx-auto d-flex justify-content-center flex-column">
        <h3 class="text-center">{{ object|yesno:"Update,Create" }} dish</h3>
        <form role="form" method="post" autocomplete="off">
          <div class="card-body">
            <div class="row justify-content-center">
              <div class="col-md-6">
                <div class="input-group input-group-dynamic mb-4">
                  {% csrf_token %}
                    {{ form.name|as_crispy_field }}
                    {{ form.description|as_crispy_field }}
                    {{ form.price|as_crispy_field }}
                </div>
                <div class="input-group input-group-dynamic mb-4">
                    {{ form.dish_type|as_crispy_field }}
                    {{ form.cooks|as_crispy_field }}
                </div>
              </div>
            </div>
            <div class="d-flex justify-content-center">
              <input type="submit" value="Submit" class="btn btn-primary" style="margin-right: 10px;">
              <a href="{% url 'restaurant:dish-list' %}" class="btn btn-secondary">Cancel</a>
            </div>
          </div>
        </form>
      </div>
    </div>
  </div>
</section>

{% endblock %}

templates/restaurant/dish_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">


{% block content %}

    <header class="bg-gradient-dark">
    <div class="page-header" style="background-image: url('{{ ASSETS_ROOT }}/img/dish_list.jpg'); min-height: 50vh;">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">Dish list</h1>
            <a href="{% url 'restaurant:dish-create' %}" class="btn btn-primary link-to-page">Create</a>
          </div>
        </div>
      </div>
    </div>
  </header>


  {% include "includes/search_form.html" %}

  {% if dish_list %}
    <div class="card-body p-0">
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
          <div class="table-responsive">
            <div class="customer-scroll" style="height:auto;position:relative;">
              <table class="table table-hover m-b-0" style="table-layout: auto;">
                <thead>
                  <tr>
                    <th><span>ID</span></th>
                    <th><span>Name<a class="help" data-toggle="popover"><i class="feather icon-help-circle f-16"></i></a></span></th>
                    <th><span>Price<a class="help" data-toggle="popover"><i class="feather icon-help-circle f-16"></i></a></span></th>
                    <th><span>Dish type<a class="help" data-toggle="popover"><i class="feather icon-help-circle f-16"></i></a></span></th>
                  </tr>
                </thead>
                <tbody>
                {% for dish in dish_list %}
                  <tr>
                    <td>
                      {{ dish.id }}
                    </td>
                    <td>
                      <a href="{{ dish.get_absolute_url }}">{{ dish.name }}</a>
                    </td>
                    <td>
                      {{ dish.price }}
                    </td>
                    <td>
                      {{ dish.dish_type }}
                    </td>
                  </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

  {% else %}
      <p>There are no dishes in the restaurant.</p>
  {% endif %}
{% endblock %}

templates/restaurant/dish_type_list.html
{% extends "layouts/base.html" %}
{% load crispy_forms_filters %}
{% load static %}
    <link rel="stylesheet" href="{% static 'css/styles.css' %}">

{% block content %}

    <header class="bg-gradient-dark">
    <div class="page-header" style="background-image: url('{{ ASSETS_ROOT }}/img/dish_types.jpg'); min-height: 50vh;">
      <span class="mask bg-gradient-dark opacity-6"></span>
      <div class="container">
        <div class="row justify-content-center">
          <div class="col-lg-8 text-center mx-auto my-auto">
            <h1 class="text-white">Dish type list</h1>
            <a href="{% url 'restaurant:dish-type-create' %}" class="btn btn-primary link-to-page">Create</a>
          </div>
        </div>
      </div>
    </div>
  </header>


  {% include "includes/search_form.html" %}

  {% if dish_type_list %}
    <div class="card-body p-0">
      <div class="tab-content" id="pills-tabContent">
        <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
          <div class="table-responsive">
            <div class="customer-scroll" style="height:auto;position:relative;">
              <table class="table table-hover m-b-0" style="table-layout: auto;">
                <thead>
                  <tr>
                    <th><span>ID</span></th>
                    <th><span>Name<a class="help" data-toggle="popover"><i class="feather icon-help-circle f-16"></i></a></span></th>
                    <th><span>Update<a class="help" data-toggle="popover"><i class="feather icon-help-circle f-16"></i></a></span></th>
                    <th><span>Delete<a class="help" data-toggle="popover"><i class="feather icon-help-circle f-16"></i></a></span></th>
                  </tr>
                </thead>
                <tbody>
                {% for dish_type in dish_type_list %}
                  <tr>
                    <td>
                      {{ dish_type.id }}
                    </td>
                    <td>
                      {{ dish_type.name }}
                    </td>
                    <td>
                      <a href="{% url 'restaurant:dish-type-update' pk=dish_type.id %}">
                       Update
                      </a>
                    </td>
                    <td>
                      <a href="{% url 'restaurant:dish-type-delete' pk=dish_type.id %}" style="color: red;">
                       Delete
                      </a>
                    </td>
                  </tr>
                {% endfor %}
              </table>
            </div>
          </div>
        </div>
      </div>
    </div>

  {% else %}
      <p>There are no dish types in the service.</p>
  {% endif %}
{% endblock %}